.TH ocrtype 1 "2024-10-14" "0.1" "Read and write text on the screen."
.SH NAME
ocrtype - OCR read from a screen area into clipboard or type clipboard contents.
.SH SYNOPSIS
.SY
ocrtype MODE [options]...
.YS
.SH DESCRIPTION
ocrtype is a bash(1) shell script to read text in an area of the screen
or type text stored in the clipboard.
.SH MODES
.B "r"
.IP
Read mode - Read text displayed on a selected area of the screen.
.P
.B "w"
.IP
Write mode - Types the text stored in the clipboard after a delay.
.P
.SH OPTIONS
.B TODO
